# Generated by Django 5.0 on 2023-12-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosDeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=12)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField(verbose_name=200)),
            ],
        ),
        migrations.CreateModel(
            name='Intereses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autos', models.BooleanField()),
                ('animales', models.BooleanField()),
                ('medioambiente', models.BooleanField()),
                ('viajes', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
